# This file was generated by GoReleaser. DO NOT EDIT.
cask "komplete" do
  name "komplete"
  desc "AI shell assistant - natural language to commands and inline autocomplete"
  homepage "https://github.com/zeke-john/komplete"
  version "0.0.1-0b6fa04"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "komplete"

  on_macos do
    on_arm do
      url "https://github.com/zeke-john/komplete/releases/download/v#{version}/komplete_darwin_arm64.tar.gz"
      sha256 "d04fb3d6d1e32420d20d99baf650dec27ab8d7a5851262561aff7053108d692e"
    end
  end

  caveats do
    "Get started:"
    "  komplete config set openrouter_api_key YOUR_KEY"
    ""
    "Optional alias, add to .zshrc:"
    "  alias k=komplete"
    ""
    "Optional autocomplete, add to .zshrc:"
    "  komplete config set groq_api_key YOUR_KEY"
    "Then run: komplete init zsh"
  end

  # No zap stanza required
end
